# language: php 

build:

  nodes:

    tests: true

    analysis:

      tests:

        override:

          -

            command: phpcs-run

            use_website_config: true

          - php-scrutinizer-run



checks:

  php:

    unused_variables: true

    unused_properties: true

    unused_parameters: true

    unused_methods: true

    unreachable_code: true

    return_in_constructor: true

    verify_access_scope_valid: true

    variable_existence: true

    use_statement_alias_conflict: true

    parameter_non_unique: false

filter:
  excluded_paths:
    - tests/*
    - "src/voku/Resources/Utf8.php"