<?php

namespace devtoolboxuk\soteria\Wrappers\Resources;

/**
 *
 * Full list from here - https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes
 *
 * Class HtmlAttributesArray
 * @package devtoolboxuk\soteria\Wrappers\Resources
 */
class HtmlAttributesArray
{

    private $dataArray = [
        'accept',
        'accept-charset',
        'accesskey',
        'action',
        'align',
        'allow',
        'alt',
        'async',
        'autocapitalize',
        'autocomplete',
        'autofocus',
        'autoplay',
        'bgcolor',
        'border',
        'buffered',
        'challenge',
        'charset',
        'checked',
        'cite',
        'class',
        'code',
        'codebase',
        'color',
        'cols',
        'colspan',
        'content',
        'contenteditable',
        'contextmenu',
        'controls',
        'coords',
        'crossorigin',
        'csp ',
        'data',
        'datetime',
        'decoding',
        'default',
        'defer',
        'dir',
        'dirname',
        'disabled',
        'download',
        'draggable',
        'dropzone',
        'enctype',
        'for',
        'form',
        'formaction',
        'headers',
        'height',
        'hidden',
        'high',
        'href',
        'hreflang',
        'http-equiv',
        'icon',
        'id',
        'importance ',
        'integrity',
        'ismap',
        'itemprop',
        'keytype',
        'kind',
        'label',
        'lang',
        'language',
        'lazyload ',
        'list',
        'loop',
        'low',
        'manifest',
        'max',
        'maxlength',
        'minlength',
        'media',
        'method',
        'min',
        'multiple',
        'muted',
        'name',
        'novalidate',
        'open',
        'optimum',
        'pattern',
        'ping',
        'placeholder',
        'poster',
        'preload',
        'radiogroup',
        'readonly',
        'referrerpolicy',
        'rel',
        'required',
        'reversed',
        'rows',
        'rowspan',
        'sandbox',
        'scope',
        'scoped',
        'selected',
        'shape',
        'size',
        'sizes',
        'slot',
        'span',
        'spellcheck',
        'src',
        'srcdoc',
        'srclang',
        'srcset',
        'start',
        'step',
        'style',
        'summary',
        'tabindex',
        'target',
        'title',
        'translate',
        'type',
        'usemap',
        'value',
        'width',
        'wrap'
    ];

    function getData()
    {
        return $this->dataArray;
    }
}